[package]
name = "rec3"
version = "0.1.0"
authors = ["syedghufranhassan"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
text_io = "*"
